version: '3.4'

services:
  streamlit-app:
    image: streamlitfrontend
    container_name: streamlitapp
    ports:
      - 8501:8501
    working_dir: /usr/src/app
    
    
  data-api:
    image: fastapibackend
    container_name: skillskeletonapi
    ports:
      - 8000:8000
    working_dir: /usr/src/api
